export const navbar = [
  {
    id: 0,
    path: "/",
    element: <h1>Home</h1>,
    title: "Home",
    private: false,
    hidden: false,
  },
  {
    id: 2,
    path: "/properties",
    element: <h1>Properties</h1>,
    title: "Properties",
    private: false,
    hidden: false,
  },
  {
    id: 3,
    path: "/contacts",
    element: <h1>Contacts</h1>,
    title: "Contacts",
    private: false,
    hidden: false,
  },
  {
    id: 4,
    path: "/signin",
    element: <h1>Signin</h1>,
    title: "Signin",
    private: false,
    hidden: true,
  },
  {
    id: 5,
    path: "/signup",
    element: <h1>Signup</h1>,
    title: "Signup",
    private: false,
    hidden: true,
  },
];
